included:
    - EastAsianWidth/

line_length: 120
file_length: 500

variable_name:
  excluded:
    - EastAsianAmbiguousCharacterSet
    - EastAsianHalfwidthCharacterSet
    - EastAsianFullwidthCharacterSet
    - EastAsianNarrowCharacterSet
    - EastAsianNeutralCharacterSet
    - EastAsianWideCharacterSet
