branches:
  only: master
matrix:
  include:
    - os: osx
      osx_image: xcode8.2
      language: generic
      script:
        - swift build
        - swift test
      env:
        - JOB=SWIFTPM_DARWIN
